package jbilling;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PrinterException;
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterJob;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
/**
 *
 * @author SKIDDOW
 */
public class MainJFrame extends javax.swing.JFrame {

    Connection conn = null;
    
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null); //Open JFrame in center Screen
        this.setResizable(false); // Disable window resizing
        conn = MySQLConnection.Connect();       
        LoadData();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ItemCodejComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ItemNamejLabel = new javax.swing.JLabel();
        ItemNamejLabel1 = new javax.swing.JLabel();
        PricejLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BilljTable = new javax.swing.JTable();
        AddjButton = new javax.swing.JButton();
        totaljLabel = new javax.swing.JLabel();
        totaljLabel1 = new javax.swing.JLabel();
        PrintjButton = new javax.swing.JButton();
        QtyjTextField = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        AddNewItemjMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JBilling System");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("JBilling System");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Item code");

        ItemCodejComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ItemCodejComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemCodejComboBoxItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Qty.");

        ItemNamejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ItemNamejLabel.setText("[item_name]");

        ItemNamejLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ItemNamejLabel1.setText("Price");

        PricejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PricejLabel.setText("[price]");

        BilljTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BilljTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Price", "Qty.", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(BilljTable);
        if (BilljTable.getColumnModel().getColumnCount() > 0) {
            BilljTable.getColumnModel().getColumn(0).setMaxWidth(100);
            BilljTable.getColumnModel().getColumn(2).setMaxWidth(200);
            BilljTable.getColumnModel().getColumn(3).setMaxWidth(50);
            BilljTable.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        AddjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddjButton.setText("Add");
        AddjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjButtonActionPerformed(evt);
            }
        });

        totaljLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totaljLabel.setText("[total]");

        totaljLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totaljLabel1.setText("Bill TOTAL");

        PrintjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrintjButton.setText("Print");
        PrintjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintjButtonActionPerformed(evt);
            }
        });

        QtyjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QtyjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QtyjTextFieldKeyTyped(evt);
            }
        });

        jMenu.setText("File");

        AddNewItemjMenu.setText("Add new item");
        AddNewItemjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewItemjMenuActionPerformed(evt);
            }
        });
        jMenu.add(AddNewItemjMenu);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(totaljLabel1)
                            .addGap(40, 40, 40)
                            .addComponent(totaljLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(ItemNamejLabel1)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AddjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(PricejLabel)
                                .addComponent(ItemCodejComboBox, 0, 120, Short.MAX_VALUE)
                                .addComponent(PrintjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(QtyjTextField))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ItemNamejLabel)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ItemCodejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemNamejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemNamejLabel1)
                    .addComponent(PricejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(QtyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AddjButton)
                        .addGap(18, 18, 18)
                        .addComponent(PrintjButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totaljLabel)
                    .addComponent(totaljLabel1))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewItemjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewItemjMenuActionPerformed
        ItemsJFrame fm = new ItemsJFrame();
        fm.show();
    }//GEN-LAST:event_AddNewItemjMenuActionPerformed

    private void ItemCodejComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ItemCodejComboBoxItemStateChanged
        int index = ItemCodejComboBox.getSelectedIndex();
        if (index >= 0){
            conn = MySQLConnection.Connect();
            try {
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT item_name, price FROM items WHERE item_code="+ItemCodejComboBox.getSelectedItem().toString());
                while(rs.next()){
                    ItemNamejLabel.setText(rs.getString(1));
                    PricejLabel.setText(rs.getString(2));
                } 
                conn.close();         
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            QtyjTextField.setText("1");
            
        }
        
    }//GEN-LAST:event_ItemCodejComboBoxItemStateChanged

    private void AddjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddjButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) BilljTable.getModel();
        double price = Double.parseDouble(PricejLabel.getText());
        double qty = Double.parseDouble(QtyjTextField.getText());
        double value = price * qty;
        
        try {
            model.addRow(new Object[]{
                ItemCodejComboBox.getSelectedItem().toString(), 
                ItemNamejLabel.getText(), 
                price,
                qty, 
                value  });    
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        // Calculate total bill
        double total = 0;            
        for (int i = 0; i < BilljTable.getRowCount(); i++){
            double val = (double) BilljTable.getModel().getValueAt(i, 4);
            total = total + val;
            
            totaljLabel.setText(Double.toString(total));
        }
        
        ItemNamejLabel.setText("[item_name]");
        PricejLabel.setText("[price]");
        QtyjTextField.setText("1");
        ItemCodejComboBox.setSelectedIndex(-1);
        
        
    }//GEN-LAST:event_AddjButtonActionPerformed
    
    private void PrintjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintjButtonActionPerformed
        Printing pt = new Printing();
        pt.job.setPrintable(new Printing());
        //boolean doPrint = pt.job.printDialog();
        
        try {
            pt.job.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_PrintjButtonActionPerformed

    private void QtyjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyjTextFieldKeyTyped
        // Allow only numbers ======= 
        char c = evt.getKeyChar();        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_QtyjTextFieldKeyTyped

// Document: https://docs.oracle.com/javase/tutorial/2d/printing/printable.html
public class Printing implements Printable {
    
    PrinterJob job = PrinterJob.getPrinterJob();
    public int print(Graphics g, PageFormat pf, int page) throws PrinterException {

    // We have only one page, and 'page'
    // is zero-based
    if (page > 0) {
         return NO_SUCH_PAGE;
    }

    // User (0,0) is typically outside the
    // imageable area, so we must translate
    // by the X and Y values in the PageFormat
    // to avoid clipping.
    Graphics2D g2d = (Graphics2D)g;
    g2d.translate(pf.getImageableX(), pf.getImageableY());

    g.setFont(new Font("Monospaced",Font.PLAIN,11));
    g.drawString("_____________________________________________", 1, 1);
    g.drawString("_____________________________________________", 1, 12);
    g.drawString("Item", 1, 12);
    g.drawString("Price", 40, 12);
    g.drawString("Qty.", 130, 12);
    g.drawString("Value", 220, 12);
    g.drawString("|", 300, 12);
    // Now we perform our rendering
    int y = 5;
    for (int i = 0; i < BilljTable.getRowCount(); i++){
        y += 10;
        g.drawString(BilljTable.getModel().getValueAt(i, 0).toString(), 1, y+y); // Item code
        g.drawString(BilljTable.getModel().getValueAt(i, 1).toString(), 30, y+y); // Item name
        g.drawString(BilljTable.getModel().getValueAt(i, 2).toString(), 40, y+y+10); // Price 
        g.drawString(BilljTable.getModel().getValueAt(i, 3).toString(), 130, y+y+10); // qty
        g.drawString(BilljTable.getModel().getValueAt(i, 4).toString(), 220, y+y+10); // value
    }     
    g.drawString("TOTAL", 1, y+y+30);
    g.drawString(totaljLabel.getText(), 220, y+y+30);

    // tell the caller that this page is part
    // of the printed document
    return PAGE_EXISTS;
  }
    
}
    
    
    private void LoadData(){
        conn = MySQLConnection.Connect();
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT item_code FROM items");
            while(rs.next())  
            ItemCodejComboBox.addItem(rs.getString(1));
            conn.close();         
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        ItemCodejComboBox.setSelectedIndex(-1); 
        ItemNamejLabel.setText("[item_name]");
        PricejLabel.setText("[price]");
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddNewItemjMenu;
    private javax.swing.JButton AddjButton;
    private javax.swing.JTable BilljTable;
    private javax.swing.JComboBox<String> ItemCodejComboBox;
    private javax.swing.JLabel ItemNamejLabel;
    private javax.swing.JLabel ItemNamejLabel1;
    private javax.swing.JLabel PricejLabel;
    private javax.swing.JButton PrintjButton;
    private javax.swing.JTextField QtyjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel totaljLabel;
    private javax.swing.JLabel totaljLabel1;
    // End of variables declaration//GEN-END:variables
}
